a = int(input("Enter first no"))
b = int(input("enter second no"))
print("-----Calculator----- ")
print("addition",a+b)
print("subraction",a-b)
print("multiplication",a*b)
print("division",a/b)
print ("power",a**b)
print ("modulus",a%b)
print("floor division",a//b)