name = input("enter name")
age = input("Enter age")
College =input("Enter clg name")
branch =input("Enter branch ")
print("---Student name--")
print ("Name :",name)
print ("Age :",age)
print ("College :",College) 
print ("Branch :",branch)